import xml.etree.ElementTree as ET

valid_airport_xml = ET.fromstring("""
<AIRPORTS>
    <AIRPORT>
      <RECORD_TYPE>PA</RECORD_TYPE>
      <AIRPORT_IDENTIFIER>KJFK</AIRPORT_IDENTIFIER>
      <ICAO_CODE>KJFK</ICAO_CODE>
      <AIRPORT_NAME>JOHN F KENNEDY INTL</AIRPORT_NAME>
      <CITY_NAME>NEW YORK</CITY_NAME>
      <STATE_CODE>NY</STATE_CODE>
      <COUNTRY_CODE>US</COUNTRY_CODE>
      <POSITION>
        <LATITUDE>40.639751</LATITUDE>
        <LONGITUDE>-73.778925</LONGITUDE>
      </POSITION>
      <ELEVATION>13</ELEVATION>
      <MAGNETIC_VARIATION>13W</MAGNETIC_VARIATION>
      <TRANSITION_ALTITUDE>7000</TRANSITION_ALTITUDE>
      <TRANSITION_LEVEL>180</TRANSITION_LEVEL>
      <SPEED_LIMIT>250</SPEED_LIMIT>
      <SPEED_LIMIT_ALTITUDE>10000</SPEED_LIMIT_ALTITUDE>
      <LONGEST_RUNWAY>14323</LONGEST_RUNWAY>
    </AIRPORT>
</AIRPORTS>
""")

invalid_airport_xml = ET.fromstring("""
<AIRPORTS>
    <AIRPORT>
      <RECORD_TYPE>PA</RECORD_TYPE>
      <AIRPORT_IDENTIFIER>KJFK</AIRPORT_IDENTIFIER>
      <ICAO_CODE>KJFK</ICAO_CODE>
      <AIRPORT_NAME>JOHN F KENNEDY INTL</AIRPORT_NAME>
      <CITY_NAME>NEW YORK</CITY_NAME>
      <STATE_CODE>NY</STATE_CODE>
      <COUNTRY_CODE>US</COUNTRY_CODE>
      <POSITION>
        <LATITUDE>Not found</LATITUDE>
        <LONGITUDE>-73.778925</LONGITUDE>
      </POSITION>
      <ELEVATION>13</ELEVATION>
      <MAGNETIC_VARIATION>13W</MAGNETIC_VARIATION>
      <TRANSITION_ALTITUDE>7000</TRANSITION_ALTITUDE>
      <TRANSITION_LEVEL>180</TRANSITION_LEVEL>
      <SPEED_LIMIT>250</SPEED_LIMIT>
      <SPEED_LIMIT_ALTITUDE>10000</SPEED_LIMIT_ALTITUDE>
      <LONGEST_RUNWAY>14323</LONGEST_RUNWAY>
    </AIRPORT>
</AIRPORTS>
""")
